version: "3.9"

services:
  bot:
    image: amanzanero/cronnouncer-bot
    volumes:
      - .env:/usr/src/app/.env
      - ./service-key.json:/usr/src/app/service-key.json
    network_mode: "host"

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432
