version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build-lint-and-unit:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm audit
      - run: npm run build:dryrun
      - run: npm run lint
      - run: npm run test:unit

  end2end:
    docker:
      - image: circleci/node:14
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres123
          PG_DB: postgres
          PG_PORT: 5432
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres123
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run coverage

workflows:
  cronnouncer-ci:
    jobs:
      - build-lint-and-unit
      - end2end:
          requires:
            - build-lint-and-unit
      - deployhold:
          type: approval
          requires:
            - end2end
          filters:
            branches:
              only:
                - main
