version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  build-and-lint:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run: npm audit
      - run: npm run build:dryrun
      - run: npm run lint

  unit:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - node/install-packages
      - run: npm run test:unit

  integration:
    docker:
      - image: circleci/node:14
        environment:
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres123
          PG_DB: postgres
          PG_PORT: 5432
      - image: postgres
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres123
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run: npm run build && npm run migration:run
      - run: npm run test:integration

  release:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - setup_remote_docker
      - run:
          name: release
          command: |
            docker build -t amanzanero/cronnouncer-bot .
            npm run semantic-release --dryRun

  deploy:
    machine: true
    steps:
      - checkout
      - add_ssh_keys
      - run: |
          ssh-keyscan -H $DEPLOY_HOST >> ~/.ssh/know_hosts
          ssh root@$DEPLOY_HOST '/root/cronnouncer/deploy.sh'

workflows:
  cronnouncer-ci:
    jobs:
      - build-and-lint
      - unit:
          requires:
            - build-and-lint
      - integration:
          requires:
            - build-and-lint
      - deployhold:
          type: approval
          requires:
            - unit
            - integration
          filters:
            branches:
              only:
                - main
      - release:
          requires:
            - deployhold
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - release
          filters:
            branches:
              only:
                - main
