version: 2.1
orbs:
  node: circleci/node@3.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run build:dryrun

  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint

  coverage:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run coverage

workflows:
  build-lint-and-test:
    jobs:
      - build
      - lint
      - coverage
      - deployhold:
            type: approval
            requires:
              - build
              - lint
              - coverage
            filters:
              branches:
                only:
                  - main
